### ISSUE TITLE
Please provide a working Python example

### ISSUE THREAD

**Issue by merkys** [himynameisfuego/decomposeSTN#2]
Thank you for fixing the Python usage example (#1).

However, I fail to analyze a real-life wave file:
```Python
from scipy.io import wavfile
import decomposeSTN as STN

Fs = 44100                                                                                                                                                                                                 
nWin1 = 8192
nWin2 = 512

_, audioInput = wavfile.read("Input/Billie.wav")
STN.decSTN(audioInput, Fs, nWin1, nWin2)
```
This results in:
```
/usr/lib/python3/dist-packages/scipy/io/wavfile.py:272: WavFileWarning: Chunk (non-data) not understood, skipping it.
  warnings.warn("Chunk (non-data) not understood, skipping it.",
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    STN.decSTN(audioInput, Fs, nWin1, nWin2)
  File "/home/andrius/src/decomposeSTN/decomposeSTN.py", line 22, in decSTN
    f,t,X1 = sig.stft(x, fs=Fs, window=win1, nperseg=nWin1, noverlap=nHop1, return_onesided=True)
  File "/usr/lib/python3/dist-packages/scipy/signal/spectral.py", line 1171, in stft
    freqs, time, Zxx = _spectral_helper(x, x, fs, window, nperseg, noverlap,
  File "/usr/lib/python3/dist-packages/scipy/signal/spectral.py", line 1746, in _spectral_helper
    win, nperseg = _triage_segments(window, nperseg, input_length=x.shape[-1])
  File "/usr/lib/python3/dist-packages/scipy/signal/spectral.py", line 1977, in _triage_segments
    raise ValueError('window is longer than input signal')
ValueError: window is longer than input signal
```
I am not sure whether my setup (system-provided packages on Ubuntu 20.04.6) or I am plainly using it incorrectly. Thus it would be very nice to see a complete example of how to process a wave file with decomposeSTN.

**Comment by Vinctekan** [comment]
Good day!

I know I'm well over 1 year late to this problem, and all interest has dwindled from this project, but I'm confident I managed to get a working inference for this, which gives results that are indistinguishable from the examples in the 'Output' folder. I named it 'inference.py'. Now it uses the same variables, and parameters that is shown in the example for decomposition part of the process, but also includes measurements like checking of the sample rate matches the Fs value, and if it's stereo, it converts it to mono, and actually uses something like soundfile to actually write the dang the 3 files instead of doing nothing with it. It uses the exact same 'Billie.wav' in the 'Input' folder as the input, and I have given it a complete separate output folder path 'Output2' just to compare the 2 results, but you can remove the '2' in the name to match the output folder.

I wanted to get this to work because I have a feeling that this could be considered the 'SOTA' (state of the art) of demixing components like sines, transients, noise accurately, and also to just compare difference methods from different sources

`import os
import numpy as np
import soundfile as sf
import decomposeSTN as STN

def save_audio(audio_data, sample_rate, file_path):
    """Save audio data to a file."""
    sf.write(file_path, audio_data, sample_rate)

def decompose_and_save(input_audio_path, output_dir, Fs, nWin1, nWin2):
    """Decompose the audio into sines, transients, and noise, and save them."""
    # Load input audio
    audio, sample_rate = sf.read(input_audio_path)
    
    if sample_rate != Fs:
        raise ValueError(f"Sample rate of the input audio ({sample_rate} Hz) does not match the specified Fs ({Fs} Hz).")

    # Ensure mono input
    if audio.ndim > 1:
        audio = np.mean(audio, axis=1)  # Convert to mono by averaging channels

    # Perform decomposition
    xs, xt, xn = STN.decSTN(audio, Fs, nWin1, nWin2)

    # Create output directory if it doesn't exist
    os.makedirs(output_dir, exist_ok=True)

    # Extract the filename without extension
    filename_without_ext = os.path.splitext(os.path.basename(input_audio_path))[0]

    # Define output file paths with filename prefix
    sines_path = os.path.join(output_dir, f"{filename_without_ext}_sines.wav")
    transients_path = os.path.join(output_dir, f"{filename_without_ext}_transients.wav")
    noise_path = os.path.join(output_dir, f"{filename_without_ext}_noise.wav")

    # Save outputs
    save_audio(xs, Fs, sines_path)
    save_audio(xt, Fs, transients_path)
    save_audio(xn, Fs, noise_path)

    print(f"Saved sines to: {sines_path}")
    print(f"Saved transients to: {transients_path}")
    print(f"Saved noise to: {noise_path}")

if __name__ == "__main__":
    # User-defined parameters
    input_audio_path = "Input/Billie.wav"  # Path to the input audio file
    output_dir = "Output2/"      # Directory to save decomposed audio

    # Recommended parameters from the author
    Fs = 44100  # Sampling frequency
    nWin1 = 8192  # Window size for round 1
    nWin2 = 512   # Window size for round 2

    # Decompose and save
    decompose_and_save(input_audio_path, output_dir, Fs, nWin1, nWin2)
`

I actually compared if the output of my inference and the output in the project actually match by inverting/subtracting 1 out of the other. What I found out that the results in 'Output' actually have 0.25 second fade-in and fade-out added to each part of the output. Now I'm not sure what part does that, but I thought it was completely unnecessary so it's removed in this inference. Other than that, if you compare the 2 outputs side by side on a spectrogram viewer in something like Spectralayers, they are the same.

Side notes:
1. If you would like to process a stereo audio file, just split the audio into left and right, process the left and right channel individually, then recombine them at the end.
2. Same thing if you wanna process a file with a bigger or smaller sample rate than 44100 or the value of Fs, just change the rate manually, process the version of the audio that has the same rate, and change it back for each output after processing.

**Comment by merkys** [comment]
Thanks a lot for working example, @Vinctekan! I have not tried it out myself, but will do as soon as I have some spare cycles.
